FROM confluentinc/cp-kafka:7.7.1

EXPOSE 9092 9999 29092 29093

# Setting environment variables
ENV CLUSTER_ID="1" \
    KAFKA_PROCESS_ROLES="broker,controller" \
    KAFKA_NODE_ID="1" \
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT" \
    KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092" \
    KAFKA_CONTROLLER_QUORUM_VOTERS="1@kafka:29093" \
    KAFKA_LISTENERS="PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092" \
    KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER" \
    KAFKA_INTER_BROKER_LISTENER_NAME="PLAINTEXT" \
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="1"
